# Generated by Django 4.2.18 on 2025-01-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('post', '0002_remove_post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
