# Generated by Django 4.2.18 on 2025-02-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_name'),
        ('post', '0003_post_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(related_name='posts', to='store.product'),
        ),
    ]
