# Generated by Django 4.2.18 on 2025-02-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_creator_like_user_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
