# Generated by Django 4.2.18 on 2025-02-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='Store', max_length=100),
            preserve_default=False,
        ),
    ]
