# Generated by Django 4.2.18 on 2025-02-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('store', '0002_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image.image'),
        ),
    ]
