# Generated by Django 4.2.18 on 2025-02-12 00:02

from django.db import migrations, models

def preload_categories(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    Category.objects.bulk_create([
        Category(name='Electronics', slug='electronics'),
        Category(name='Fashion & Accesories', slug='fashion-accesories'),
        Category(name='Home', slug='home'),
        Category(name='Toys', slug='toys'),
        Category(name='Beauty & Health', slug='beauty-health'),
        Category(name='Sports', slug='sports'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RunPython(preload_categories),
    ]
